import os
from dotenv import load_dotenv

load_dotenv()

POLYMARKET_API_URL = "https://clob.polymarket.com"
POLYMARKET_GRAPHQL_URL = "https://gamma-api.polymarket.com/markets"
GIGABRAIN_BASE_URL = "https://api.gigabrain.gg"
POLYGON_RPC_URL = "https://polygon-rpc.com"
USDC_CONTRACT = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"

PRICE_SPIKE_THRESHOLD = 0.015
VOLUME_SPIKE_THRESHOLD = 1.5
POLL_INTERVAL = 1
MARKET_LIMIT = 50
MIN_MARKET_LIQUIDITY = 1000.0
ENABLE_PRICE_ALERTS = True
ENABLE_VOLUME_ALERTS = True

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

MAX_POSITION_SIZE = 100.0
MIN_PROFIT_PCT = 2.0
MAX_LOSS_PCT = -5.0
MAX_POSITIONS = 5
ENABLE_TRADING = True

POLYMARKET_API_KEY = os.getenv('POLYMARKET_API_KEY', '')
POLYMARKET_API_SECRET = os.getenv('POLYMARKET_API_SECRET', '')
POLYMARKET_PASSPHRASE = os.getenv('POLYMARKET_PASSPHRASE', '')
GIGABRAIN_API_KEY = os.getenv('GIGABRAIN_API_KEY', '')
PRIVATE_KEY = os.getenv('PRIVATE_KEY', '')
MNEMONIC = os.getenv('MNEMONIC', '')
WALLET_ADDRESS = os.getenv('WALLET_ADDRESS', '')
PROXY_WALLET = os.getenv('PROXY_WALLET', '')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')
DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL', '')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')
