import os
from dotenv import load_dotenv

load_dotenv()

POLYMARKET_API_URL = os.getenv('POLYMARKET_API_URL')
POLYMARKET_GRAPHQL_URL = os.getenv('POLYMARKET_GRAPHQL_URL')
GIGABRAIN_BASE_URL = os.getenv('GIGABRAIN_BASE_URL')
POLYGON_RPC_URL = os.getenv('POLYGON_RPC_URL')
USDC_CONTRACT = os.getenv('USDC_CONTRACT')

PRICE_SPIKE_THRESHOLD = float(os.getenv('PRICE_SPIKE_THRESHOLD', '0.015'))
VOLUME_SPIKE_THRESHOLD = float(os.getenv('VOLUME_SPIKE_THRESHOLD', '1.5'))
POLL_INTERVAL = int(os.getenv('POLL_INTERVAL', '1'))
MARKET_LIMIT = int(os.getenv('MARKET_LIMIT', '50'))
MIN_MARKET_LIQUIDITY = float(os.getenv('MIN_MARKET_LIQUIDITY', '1000.0'))
ENABLE_PRICE_ALERTS = os.getenv('ENABLE_PRICE_ALERTS', 'true').lower() == 'true'
ENABLE_VOLUME_ALERTS = os.getenv('ENABLE_VOLUME_ALERTS', 'true').lower() == 'true'

REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
REDIS_DB = int(os.getenv('REDIS_DB', '0'))

MAX_POSITION_SIZE = float(os.getenv('MAX_POSITION_SIZE', '100.0'))
MIN_PROFIT_PCT = float(os.getenv('MIN_PROFIT_PCT', '2.0'))
MAX_LOSS_PCT = float(os.getenv('MAX_LOSS_PCT', '-5.0'))
MAX_POSITIONS = int(os.getenv('MAX_POSITIONS', '5'))
ENABLE_TRADING = os.getenv('ENABLE_TRADING', 'true').lower() == 'true'

POLYMARKET_API_KEY = os.getenv('POLYMARKET_API_KEY')
POLYMARKET_API_SECRET = os.getenv('POLYMARKET_API_SECRET')
POLYMARKET_PASSPHRASE = os.getenv('POLYMARKET_PASSPHRASE')
GIGABRAIN_API_KEY = os.getenv('GIGABRAIN_API_KEY')
PRIVATE_KEY = os.getenv('PRIVATE_KEY')
MNEMONIC = os.getenv('MNEMONIC')
WALLET_ADDRESS = os.getenv('WALLET_ADDRESS')
PROXY_WALLET = os.getenv('PROXY_WALLET')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
DUNE_API_KEY = os.getenv('DUNE_API_KEY')
